import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import { Inter, Roboto_Mono } from 'next/font/google';
import Footer from '@/components/Footer';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});

const roboto_mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${roboto_mono.variable} antialiased flex flex-col relative`}
            >
                <Header />
                <div className="flex-1 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
