import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/header/Header';
import { Inter, Roboto_Mono } from 'next/font/google'

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

const roboto_mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.variable} ${roboto_mono.variable} antialiased flex flex-col`}
        >
        <Header/>
        <div className='flex-1'>
            {children}
        </div>

        </body>
        </html>
    );
}
